select
    fixture_id,
    team_id,
    team_name,
    player_id,
    player_name,
    games_minutes,
    games_position,
    shots_total,
    shots_on,
    goals_total,
    response_hash,
    player_name_normalized,
    team_name_normalized,
    fixture_date_utc,
    league_id,
    league_name,
    league_season,
    opponent_team_id,
    shots_per_90,
    shots_on_per_90,
    current_timestamp() as updated_at_utc
from {{ ref('fct_football__player_match_features') }}
